<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="python\Models\faster-whisper-small\**" />
    <EmbeddedResource Remove="python\Models\faster-whisper-small\**" />
    <None Remove="python\Models\faster-whisper-small\**" />
    <Page Remove="python\Models\faster-whisper-small\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="OllamaSharp" Version="5.4.23" />
  </ItemGroup>

  <ItemGroup>
  <None Include="python\**\*.*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
  </ItemGroup>

</Project>
